server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default--filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

#        - id: recommendation-service
#          uri: lb://recommendation-service
#          predicates:
#            - Path=/recommendation-service/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/recommendation-service/(?<segment>.*), /$\{segment}

#        - id: vote-service
#          uri: lb://vote-service
#          predicates:
#            - Path=/vote-service/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/vote-service/(?<segment>.*), /$\{segment}
