#DB
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: 1234
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: yumst

BASE_URL: http://localhost:8080
#FRONT_URL: http://localhost:8080
#FRONT_URL: http://localhost:3000
RECOMMEND_URL: http://localhost:8000

REDIS_HOST: localhost
REDIS_PORT: 6379

CHROME_DRIVER_PATH: "C:\\Users\\Leo\\chromedriver-win64\\chromedriver.exe"
