spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        dialect: org.hibernate.dialect.PostgreSQLDialect
    #    show-sql: true
    #    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

logging.level:
  org.hibernate.SQL: debug

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}