spring:
  profiles:
    include: local, jwt, oauth

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

logging.level:
  org.hibernate.SQL: debug
#  org.springframework.batch: debug
  #  org.springframework.security: debug
  #  org.springframework.web: debug
#  com.yumst.be.crawl: debug

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION}
    refresh: ${REFRESH_EXPIRATION}
  secret: ${JWT_SECRET}

etc:
  base-url: ${BASE_URL}
  front-url: ${FRONT_URL}
  front-auth-success: ${FRONT_URL}/auth/success

chrome:
  driver:
    path: "C:\\Users\\Leo\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe"