spring:
  profiles:
    include: prod, jwt, oauth

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          apple:
            client-id: ${APPLE_BUNDLE_ID}
            client-secret: ${APPLE_CLIENT_SECRET_FILE}
            redirect-uri: ${BASE_URL}/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - name
              - email
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-info-uri: https://appleid.apple.com/auth/userinfo
            user-name-attribute: sub
            issuer-uri: https://appleid.apple.com


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
      cluster:
        nodes: ${REDIS_HOST}:${REDIS_PORT}
        max-redirects: 3

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized


logging.level:
#  org.hibernate.SQL: debug
  org.springframework.web: debug
  org.springframework.security: debug
#  org.springframework.batch: debug
#  com.yumst.be.crawl: debug

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION}
    refresh: ${REFRESH_EXPIRATION}
  secret: ${JWT_SECRET}

etc:
  base-url: ${BASE_URL}
  front-url: ${FRONT_URL}
  recommend-url: ${RECOMMEND_URL}
  front-auth-success: ${FRONT_URL}/auth/success
  google-profile-url: https://www.googleapis.com/userinfo/v2/me
  apple:
    client-id: ${APPLE_BUNDLE_ID}
    client-secret: ${APPLE_CLIENT_SECRET_FILE}
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    redirect-uri: ${BASE_URL}/login/oauth2/code/apple

chrome:
  driver:
    path: ${CHROME_DRIVER_PATH}
